In [1]:
import pandas as pd
import numpy as np

from quantfreedom.backtester.indicators.talib_ind import from_talib
from quantfreedom.backtester.evaluators.evaluators import eval_is_below, eval_is_above
prices = pd.read_csv('30min.csv', index_col='time')

In [2]:
rsi_ind = from_talib(
    func_name='rsi',
    df_prices=prices,
    cart_product=False,
    combos=False,
    timeperiod=[15, 20, 30],
)

In [9]:
rsi_ind

RSI_count                    0          1          2
timeperiod                  15         20         30
time
2020-10-01 00:00:00        NaN        NaN        NaN
2020-10-01 00:30:00        NaN        NaN        NaN
2020-10-01 01:00:00        NaN        NaN        NaN
2020-10-01 01:30:00        NaN        NaN        NaN
2020-10-01 02:00:00        NaN        NaN        NaN
...                        ...        ...        ...
2021-02-22 21:30:00  55.516071  52.364915  49.668702
2021-02-22 22:00:00  51.496913  49.398176  47.611461
2021-02-22 22:30:00  49.684656  48.050665  46.671107
2021-02-22 23:00:00  45.834489  45.161627  44.639194
2021-02-22 23:30:00  49.724145  48.215568  46.868962

[6960 rows x 3 columns]

In [4]:
eval_is_below(
    rsi_ind,
    np.arange(40, 61, 5)
)

RSI_count                0                                  1                \
timeperiod              15                                 20
RSI_is_below            40     45     50     55     60     40     45     50
time
2020-10-01 00:00:00  False  False  False  False  False  False  False  False
2020-10-01 00:30:00  False  False  False  False  False  False  False  False
2020-10-01 01:00:00  False  False  False  False  False  False  False  False
2020-10-01 01:30:00  False  False  False  False  False  False  False  False
2020-10-01 02:00:00  False  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...    ...
2021-02-22 21:30:00  False  False  False  False   True  False  False  False
2021-02-22 22:00:00  False  False  False   True   True  False  False   True
2021-02-22 22:30:00  False  False   True   True   True  False  False   True
2021-02-22 23:00:00  False  False   True   True   True  False  False   True
2021-02-22 23:30:00  False  False   True   True   True  False  False   True

RSI_count                              2
timeperiod                            30
RSI_is_below            55     60     40     45     50     55     60
time
2020-10-01 00:00:00  False  False  False  False  False  False  False
2020-10-01 00:30:00  False  False  False  False  False  False  False
2020-10-01 01:00:00  False  False  False  False  False  False  False
2020-10-01 01:30:00  False  False  False  False  False  False  False
2020-10-01 02:00:00  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...
2021-02-22 21:30:00   True   True  False  False   True   True   True
2021-02-22 22:00:00   True   True  False  False   True   True   True
2021-02-22 22:30:00   True   True  False  False   True   True   True
2021-02-22 23:00:00   True   True  False   True   True   True   True
2021-02-22 23:30:00   True   True  False  False   True   True   True

[6960 rows x 15 columns]

In [8]:
eval_is_above(
    rsi_ind,
    np.arange(60, 39, -5)
)

RSI_count                0                                  1                \
timeperiod              15                                 20
RSI_is_below            60     55     50     45     40     60     55     50
time
2020-10-01 00:00:00  False  False  False  False  False  False  False  False
2020-10-01 00:30:00  False  False  False  False  False  False  False  False
2020-10-01 01:00:00  False  False  False  False  False  False  False  False
2020-10-01 01:30:00  False  False  False  False  False  False  False  False
2020-10-01 02:00:00  False  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...    ...
2021-02-22 21:30:00  False   True   True   True   True  False  False   True
2021-02-22 22:00:00  False  False   True   True   True  False  False  False
2021-02-22 22:30:00  False  False  False   True   True  False  False  False
2021-02-22 23:00:00  False  False  False   True   True  False  False  False
2021-02-22 23:30:00  False  False  False   True   True  False  False  False

RSI_count                              2
timeperiod                            30
RSI_is_below            45     40     60     55     50     45     40
time
2020-10-01 00:00:00  False  False  False  False  False  False  False
2020-10-01 00:30:00  False  False  False  False  False  False  False
2020-10-01 01:00:00  False  False  False  False  False  False  False
2020-10-01 01:30:00  False  False  False  False  False  False  False
2020-10-01 02:00:00  False  False  False  False  False  False  False
...                    ...    ...    ...    ...    ...    ...    ...
2021-02-22 21:30:00   True   True  False  False  False   True   True
2021-02-22 22:00:00   True   True  False  False  False   True   True
2021-02-22 22:30:00   True   True  False  False  False   True   True
2021-02-22 23:00:00   True   True  False  False  False  False   True
2021-02-22 23:30:00   True   True  False  False  False   True   True

[6960 rows x 15 columns]